# git-cliff Configuration File for Project: ml-energy-disaggregation

[changelog]
# Template for the changelog header
header = """
# Changelog
All notable changes to this project will be documented in this file.
"""
# Template for the changelog body (using Tera templating)
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}\n
"""
# Template for the changelog footer
footer = """
"""
# Remove the leading and trailing spaces
trim = true

# Postprocessors (Replaces the <REPO> placeholder with your actual URL)
postprocessors = [
  # This enables automatic issue linking in the changelog (e.g., #123 links to the issue)
  { pattern = '<REPO>', replace = "https://github.com/sambaiga/battery-capacity-project" },
]

# Render body even when there are no releases (useful for viewing UNRELEASED changes)
render_always = true

[git]
# Parse the commits based on https://www.conventionalcommits.org
conventional_commits = true
# Filter out the commits that are not conventional
filter_unconventional = true
# Process each line of a commit as an individual commit (leave false)
split_commits = false

# Regex for preprocessing the commit messages (Activating issue linking with the correct URL)
commit_preprocessors = [
  # Replace issue numbers (e.g., #123) with markdown links
  { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](<REPO>/issues/${2}))"},
]

# Regex for parsing and grouping commits
commit_parsers = [
  { message = "^feat", group = "🚀 Features" },
  { message = "^fix", group = "🐛 Bug Fixes" },
  { message = "^refactor", group = "🚜 Refactor" },
  { message = "^perf", group = "⚡ Performance" },
  { message = "^test", group = "🧪 Testing" },
  { message = "^build", group = "📦 Build" },
  { message = "^ci", group = "⚙️ CI/CD" },
  { message = "^chore", group = "🧹 Chore" },
  { message = "^doc", group = "📚 Documentation" },
  { message = "^style", group = "🎨 Styling" },
  { body = ".*security", group = "🛡️ Security" },
  { message = "^revert", group = "↩️ Reverts" },
  # Skips
  { message = "^chore\\(release\\): prepare for", skip = true },
  { message = "^chore\\(deps.*\\)", skip = true },
  { message = "^chore\\(pr\\)|pull", skip = true },
  # Fallback
  { message = ".*", group = "💼 Other" },
]

filter_commits = true
topo_order = false
sort_commits = "oldest"
